### ISSUE TITLE
CRM contacts associations API in 7.1.0

### ISSUE THREAD

**Issue by DragosChirila** [HubSpot/hubspot-api-python#149]
Hey,

Thank you very much for releasing 7.1.0. I had an issue myself as described here https://github.com/HubSpot/hubspot-api-python/issues/144#issuecomment-1328531537:
```
api_response = (
    api_client.crm
    .contacts
    .associations_api.create(
        contact_id=contact_id,
        to_object_type='company',
        to_object_id=company_id,
        association_type='contact_to_company'
    )
)
```

After installing 7.1.0 however, I noticed that my call doesn't work anymore throwing this error
```
AssociationsApi.create() missing 1 required positional argument: 'association_spec'
```

I've done some digging into your code and I learned that `models/association_spec.py` was added and `association_type` was replaced by `association_spec`.

I couldn't find any specs or example for this new addition. I looked into https://developers.hubspot.com/docs/api/crm/contacts but I didn't find what I was looking for.

Would you please let me know how I should update the above code to make it work with 7.1.0? 

Kind regards,
Dragos

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @DragosChirila 
Can you try this one ?
api_response =  api_client.crm.contacts.associations_api.create(
        contact_id="contact_id",
        to_object_type='company',
        to_object_id="company_id",
        association_spec=[{"associationCategory":"HUBSPOT_DEFINED","associationTypeId":1}
        )
Thanks.

**Comment by DragosChirila** [comment]
Thank you very much @alzheltkovskiy-hubspot ,
Your suggestion did the trick, this code works:
```
api_response = (
    api_client.crm
    .contacts
    .associations_api.create(
        contact_id=contact_id,
        to_object_type='company',
        to_object_id=company_id,
        association_spec=[
            {
                "associationCategory": "HUBSPOT_DEFINED",
                "associationTypeId": 1
            }
        ]
    )
)
```

Now, would you please be so kind and shed some light on `association_spec` argument:
- associationCategory -> what does `HUBSPOT_DEFINED` represent?
- associationTypeId -> what does `1` represent?

Also, would you please let us know where to find more details in the official documentation
https://developers.hubspot.com/docs/api/crm/contacts ?

Best regards,
Dragos

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @DragosChirila 
More detail about association_spec you can find [here](https://developers.hubspot.com/docs/api/crm/associations)
It should be help 
Thank you
